apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-config
  namespace: kube-system
data:
  cloud-config.conf: |
    [Global]
    KubernetesClusterTag=kubernetes
    KubernetesClusterID=kubernetes
    Zone=ap-south-1
