apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-app
  labels:
    app: news-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: news-app
  template:
    metadata:
      labels:
        app: news-app
    spec:
      containers:
      - name: news-app
        image: abdullah111111/news-app
        ports: 
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: news-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"

spec:
  selector:
    app: news-app
  type: LoadBalancer
  # type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # nodePort: 30001

