apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-storage-0
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-0ed7045524cbfcd4f 
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-storage-1
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-01e214bb38ae492a6 
    fsType: ext4

---
apiVersion: v1
kind: mongodb-storage-2
metadata:
  name: ebs-pv2
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-0c705b426559f11a8 
    fsType: ext4
